Adding accordion
BartHough/census-data-site pull request #15
Opened 2019-11-13 21:48 UTC by DRot88

Wrapped the map, form, and chart with an accordion feature.

2019-11-14 03:09 UTC, kevharvell requested changes
I think it's a good start but still needs some work before we merge it. Things that might be better:

1. Not a fan of all accordion options starting closed. I think Map and Form should start open, then close upon submit.
2. Based on #1, there shouldn't be an only 1 can be open limiter
3. None of the API calls are resulting in a graph for me. Not sure if that's just me or not.

2019-11-14 05:09 UTC, BartHough requested changes
Also the chart shouldn't be in an accordion, it'll just appear on submit and not show up in any way before... I think the accordion functionality should probably all be implemented with conditional rendering. Look at how the chart and 'Loader' components are rendered right now in master. For example, once a location is locked in, a boolean state var will be toggled and the map will be replaced with a button(or something) that says 'change location'. Same thing could be done with the form.
https://reactpatterns.com/#conditional-rendering

2019-11-19 04:55 UTC, kevharvell submitted a review, later dismissed

2019-11-19 19:46 UTC, BartHough requested changes
`How bug free is it? (50 points)
Is it easy to use? Is there clear thought given to usability and the user interface? (30 points)
Is it attractive? (15 points)
Does it meet the requirements of the project, including clear evidence of effort and product that shows about 100 hours of work per person? (155 points)`

Per the `Is it attractive` requirement, I'm not going to approve this until it looks better/implements conditional rendering, or at a minimum is fully functional and has automatic opening and closing of the tabs

2019-12-03 01:12 UTC, closed without merging